esp-rs/esp-idf-template

cargo/src/main.rs
A neat little trick I've been using with the [atomic emulation trap handler](https://github.com/esp-rs/riscv-atomic-emulation-trap/blob/bbfad4c0ecfaea59a66c28a4ecb8419f515b287f/src/lib.rs#L9) to include a dependency without unused warnings.
=> Remove `allow` declaration in favour of anonymous import

cargo/sdkconfig.defaults
By default it is 100 Hz, which means all thread sleeps under 10 ms do not work as expected.
So this would just busy wait and does not give other threads chance to run. And it can be very confusing for the user.
```rust
loop {
thread::sleep(Duration::from_millis(9))
}
```
So from user perspective it makes sense to explicitly define CONFIG_FREERTOS_HZ here. It would be less surprising then.
I learned it hard way here: https://github.com/esp-rs/esp-idf-sys/issues/71
=> add CONFIG_FREERTOS_HZ=1000 to sdkconfig.defaults

cargo/.cargo/config.toml, cargo/Cargo.toml, cargo/cargo-generate.toml, cargo/rust-toolchain.toml
v4.4 is now officially released. v4.4 has most (all?) the patches we need from the Rust side, including `realpath` so we can now remove `panic_immediate_abort` feature.
=> Default to v4.4

README-pio.md
Fixed a typo in the project creation command of the PlatformIO guide: command failed with
```
error: Found argument '--framework' which wasn't expected, or isn't valid in this context
Did you mean --frameworks?
```
=> Fixed a syntax error in the PlatformIO guide.

cargo/.devcontainer/Dockerfile, cargo/.gitpod.Dockerfile, cargo/cargo-generate.toml, cargo/docs/README.md
- Install `wokwi-server` and `web-flash` via rust installer, this will use binary packages if available
- Ignore `docs` and `script` folders when not using devcontainers.
- Install `clippy` and `rustfmt` for RustAnalyzer 
- Add `.devcontainer.json` reference link in documentation
=> Improve devcontainer support

cargo/.devcontainer/Dockerfile, cargo/.gitpod.Dockerfile, cargo/Cargo.toml
- Upgraded Rust version to `2021`
- Updated to rust toolchain to `1.62.0.0`
- Removed `--clear-cache "YES"` as it [now the default valule](https://github.com/esp-rs/rust-build/blob/597a8d97bdce2f4f33f8898592f7c9f24bd71883/install-rust-toolchain.sh#L22)
=> Toolchain and Rust edition Update

.github/workflows/ci.yml, cargo/Cargo.toml
`cargo generate` commands on the CI should use the testing repo instead of always using `esp-rs/esp-idf-tempalte` on `master` branch, so I introduced changes to use the propper repo and branch that we want to test.
=> Improve CI to allow checking PRs

README.md, cargo/.cargo/config.toml
- Add custom runner so `cargo run` flashes and open a serial monitor.
- Improve Readme so we have a short description of every prompt.
=> Add custom runner and update readme

cmake/.gitignore
A slash in the beginning or middle of a gitignore pattern causes the
pattern to match only relative to the directory of the .gitignore
file[1]. This means that the 'Cargo.lock' and 'target' patterns were
not matching anything and the build pattern was only matching the top
level build.
[1]: https://git-scm.com/docs/gitignore
=> .gitignore: fix absolute path references in cmake template

cargo/src/main.rs
Fixes #71 
I'm not very satisfied with the provided URL. It currently only tells the user *that* it's needed, not exactly why. Do you have a better link we can use that helps the user understand the reason for `link_patches`?
=> Update link_patches() comment to reflect current status

cargo/.cargo/config.toml
Replace 'espflash --monitor' with 'espflash flash --monitor'
=> Clarify target runner arguments for espflash v1.x.x and v2.x.x

cargo/Cargo.toml
fix #114 by adding patched embedded-svc in case the user uses the "Yes (all features)" option
also repairs the cargo ci
=> esp-idf-svc nightly feature needs  emb-svc master

.github/workflows/ci_cargo.yml, .github/workflows/ci_cmake.yml, README.md, cargo/.cargo/config.toml, cargo/cargo-generate.toml
As suggested by @Vollbrecht, we are renaming the esp-idf option from `mainline` to `master` to be consisten with the naming
=> Rename esp-idf option from mainline to master

cargo/src/main.rs, cmake/components/rust-{{project-name}}/src/lib.rs
The template is currently broken due to recent changes. Cargo CI still fails due to esp-idf-hal: https://github.com/SergioGasquez/esp-idf-template/actions/runs/4959728233/jobs/8874244444
=> Fix cargo template

cargo/cargo-generate.toml, cargo/pre-script.rhai
Adds the options for the esp32 c6 dev board in the cargo generate toml
=> add esp32c6

.github/workflows/ci_cargo.yml, .github/workflows/ci_cmake.yml, README.md, cargo/.cargo/config.toml, cargo/cargo-generate.toml, cargo/pre-script.rhai
- Remove esp32p4 target
- Is not supported yet, and we don't know when it will be released
- Update and simplify the conditions of the placeholders
- Replaced v5.0 for 5.1 (see #121)
- Expand CI to cover new targets
- CI is failing for `v5.1` since the [following cfg](https://github.com/esp-rs/esp-idf-hal/blob/master/src/ledc.rs#L129-L134) needs to be adjusted.
- Updated the default values for new chips.
The PR updates the changes introduced in #123, #124 #125
=> Update template for new chips

README.md
esp-rs book now uses `installation/index.html`
=> fix: dead link

cmake/components/rust-{{project-name}}/CMakeLists.txt
esp32c6 requires the riscv32imac instead of the riscv32imc rust target
=> fix: compilation for esp32c6

cargo/.github/workflows/rust_ci.yml
Set `true` to ldproxy in rust_ci.yml
As described in https://github.com/esp-rs/xtensa-toolchain#inputs , `ldproxy` property should be `true` if want to use std. So set it to `true` because this template is for using std with esp.
Actually, rust_ci fails because `ldproxy` not found in my environment.
https://github.com/ysak-y/test-esp-idf-rust/actions/runs/6214217169/job/16865945339
Set `ldproxy` property to true.
Could you please review this? @SergioGasquez
=> [nits] Make ldproxy to true in rust_ci.yml

cargo/.cargo/config.toml
To install the  correct upstream esp-idf version the env variables need to point to the full version tag.
Note: ESP_IDF_VERSION "v5.1" is a different release than "v5.1.1" 
Release Notes:
v4.4.6 https://github.com/espressif/esp-idf/releases/tag/v4.4.6
v5.1.1https://github.com/espressif/esp-idf/releases/tag/v5.1.1
=> 🔖 bump esp-idf tags

cargo/diagram.json
needed for correct terminal output in wokwi
=> 🐛 add missing TX for terminal output

cargo/Cargo.toml
While `cargo update` would provide one with the newest version we still should bump it here
=> ⬆️ bumb esp-idf-svc dep duo to breaking bug

cargo/pre-script.rhai
The wokwi_board was incorrect for esc32-c6. See https://github.com/wokwi/wokwi-features/issues/751
=> Fix c6 wokwi board component

cargo/.cargo/config.toml
I've hit this trap several times during the last weeks. #174 describes it and the solution. But every time I hit it, I just had forgotten about it which was quite annoying.
The workaround apparently does not affect Linux (while I can't test on Windows). So why not shipping it until https://github.com/esp-rs/esp-idf-hal/pull/387 gets released and the template updated?
=> Add workaround for #174, cc crate failing on macOS

cargo/Cargo.toml
introduces a workaround so people by default have a working rust-analyzer that doesn't trip over building tests for the bin crate.
RA fails over this with problems that lead to problems mention upstream https://github.com/rust-lang/rust/issues/125714
=> do not use the built in cargo test harness for bin targets

cargo/.devcontainer/devcontainer.json
This is done to address a problem in the `serialport-rs` library: https://github.com/serialport/serialport-rs/issues/153
Without this fix, `espflash` is unable to see my board's `ttyACM` node
I'm using the `runArgs` property since the `mounts` property doesn't allow specifying `readonly`.
=> Add mount for host's udev rules in container

.github/workflows/ci_cargo.yml, .github/workflows/ci_cmake.yml, README-cmake-details.md, README-cmake.md, README.md, cargo/.cargo/config.toml, cargo/Cargo.toml, cargo/cargo-generate.toml, cargo/pre-script.rhai, cmake/cargo-generate.toml, cmake/components/rust-{{project-name}}/CMakeLists.txt, cmake/components/rust-{{project-name}}/Cargo.toml, cmake/components/rust-{{project-name}}/build.rs
I think it is time to radically simplify the generated template and ask only what toolchain folks want to use:
* People routinely get confused with the `embassy` features -> make these mandatory in the generated `Cargo.toml`
* People are attempting to do `no_std` with `esp-idf-*` - which is pointless -> remove the `std` and `alloc` features from the generated `Cargo.toml`
=> Radically simplify the generated Cargo.toml

cargo/Cargo.toml
Hello there,
I spent a lot of time figuring out how to fix the following error:
```
error occurred: unknown target `riscv32imac_zicsr_zifencei-esp-espidf`
```
during `cargo build`.
Turns out the reason I had this error because I accidentally updated the cc version. I could not find any information online about the issue which lead to many hours spent trying to fix this. If the comment had the information that the cc version must be `1.1.30` I would have discovered the problem way sooner.
I suggest to include the required version number in the comment, what do you think?
=> Clarify comment about the required cc version

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Subject says it all. A few minor changes so that the PR and issue reporting templates look the same across the (not-yet-mono-repoed) `esp-idf-*` crates.
=> Unify issue and PR templates with the other esp-idf- crates

cargo/.github/workflows/rust_ci.yml
We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:
The Github CI currently fails if the target is risc-v
See [here](https://github.com/kaaax0815/smart-hot-water-tank/actions/runs/12536986335/job/34960602507) and [here](https://github.com/kaaax0815/smart-hot-water-tank/actions/runs/12537065306/job/34960766443)
- Add `rustfmt` and `clippy` to components for nightly toolchain
- Install ldproxy
In my own project https://github.com/kaaax0815/smart-hot-water-tank/commit/204e20b052220132416e99181ec923dd40da64f5
=> Fix Github CI for Risc-v targets

.github/workflows/ci_cargo.yml, CHANGELOG.md, README-cmake-details.md, README-cmake.md, README.md, cargo/.cargo/config.toml, cargo/Cargo.toml, cargo/cargo-generate.toml, cmake/components/rust-{{project-name}}/Cargo.toml
We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:
- [v] I have updated existing examples or added new ones (if applicable).
- [v] I have used `cargo fmt` command to ensure that all changed code is formatted correctly.
- [v] I have used `cargo clippy` command to ensure that all changed code passes latest Clippy nightly lints.
- [v] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-idf-template/blob/main/esp-idf-template/CHANGELOG.md) in the **_proper_** section.
As per the subject:
- `esp-idf-svc` (and `embuild`) updated to the just-released versions
- Since we finally can build ourselves against latest stable ESP-IDF, the template is changed to offer by …
=> Update to the newly-released crates; use ESP IDF V5.3 (latest stable) and V5.2 (previous stable)
